### ISSUE TITLE
bug,手机端显示异常

### ISSUE THREAD

**Issue by 2949193550** [jiewenhuang/halo-nicetheme-PandaPRO#1]
设备：redmi note12turbo，
![26dc6fb4d300e3bb862967675a64c06](https://github.com/jiewenhuang/halo-nicetheme-PandaPRO/assets/63438310/aba36bff-e015-402c-9d0a-8c8c1f1dd3f2)
建议将发布者更改为文章摘要

**Comment by jiewenhuang** [comment]
尝试填充内容以及头像后解决，建议部分，这里只是同步原主题，其他需求可以自行fork项目后修改
