### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 2949193550** [jiewenhuang/halo-nicetheme-PandaPRO#2]
1.
![image](https://github.com/jiewenhuang/halo-nicetheme-PandaPRO/assets/63438310/263757a9-f762-4f0c-952d-c44a95990a1c)
此处标题无法打开，我的建议是弄到百度的热搜榜第一来替换，或者微博

2.关于页面打不开

**Comment by jiewenhuang** [comment]
此处需要选择推荐文章
<img width="1150" alt="image" src="https://github.com/jiewenhuang/halo-nicetheme-PandaPRO/assets/68629578/1245686f-ac04-4449-8328-af85dae92ebb">
关于页面，更新主题后可用
